# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ '**' ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: jungwinter/split@v1
        id: split
        with:
          msg: github.event.head_commit.message
          seperator: '#'
      - if: steps.split.outputs._1 !== null
        name: Close Issue
        uses: peter-evans/close-issue@v1
        with:
          issue-number: steps.split.outputs._1
